# the lib name
lib.name = nextpow2

# source file
class.sources = src/nextpow2.c

# include other files
# datafiles = nextpow2-help.pd

include /home/arthur/pd/externals_tests/pd-lib-builder-master/Makefile.pdlibbuilder



